export const games = [
  {
    id: 'corte-perfecto',
    title: 'El corte perfecto',
    description: 'Tres manzanas. Una elección. Un corte.',
    url: 'https://goyoaga.github.io/corte-perfecto/',
    icon: '🍎',
    accent: '#b54434',
  },
  {
    id: 'el-aterrizaje-perfecto',
    title: 'El aterrizaje perfecto',
    description: 'Un avión de papel. Una sola suelta.',
    url: 'https://goyoaga.github.io/el-aterrizaje-perfecto/',
    icon: '✈️',
    accent: '#456b69',
  },
  {
    id: 'la-gota-exacta',
    title: 'La Gota Exacta',
    description: 'Una caída. El momento justo. Ni una gota más.',
    url: 'https://goyoaga.github.io/la-gota-exacta/',
    icon: '💧',
    accent: '#75aaf2',
  },
  {
    id: 'el-tiro-de-papel',
    title: 'El tiro de papel',
    description: 'Una bola de papel. Una papelera. Un solo tiro.',
    url: 'https://goyoaga.github.io/el-tiro-de-papel/',
    icon: '🗑️',
    accent: '#c47b55',
  },
  {
    id: 'el-amarre-perfecto',
    title: 'El Amarre Perfecto',
    description: 'Corta el motor. Después, solo mira.',
    url: 'https://goyoaga.github.io/el-amarre-perfecto/',
    icon: '⚓',
    accent: '#326f70',
  },
  {
    id: 'el-putt-perfecto',
    title: 'El Putt Perfecto',
    description: 'Un golpe. La fuerza justa. Directo al hoyo.',
    url: 'https://goyoaga.github.io/el-putt-perfecto/',
    icon: '⛳',
    accent: '#4f7354',
  },
  {
    id: 'el-hueco',
    title: 'El Hueco',
    description: 'Un globo. Dos nubes. Encuentra el hueco.',
    url: 'https://goyoaga.github.io/el-hueco/',
    icon: '☁️',
    accent: '#b85f45',
  },
];
